POST /api/phonebill/ HTTP/1.1
Content-Type: application/json

{
    "price_plan" : "sms 101",
    "actions" : "call, sms, call"
}

###
 
GET /api/price_plans/

###

POST /api/price_plan/create HTTP/1.1
Content-Type: application/json

{
    "name" : "sms 101",
    "call_cost" : 2.65,
    "sms_cost" : 0.45
}

###

POST /api/price_plan/update HTTP/1.1
Content-Type: application/json

{
    "name": "sms 101",
    "call_cost" : 2.65,
    "sms_cost": 0.45
}

###

POST /api/price_plan/delete HTTP/1.1
Content-Type: application/json

{
    "id": 17
}